packages:
  - 'packages/*'
  - 'tools/*'
allowBuilds:
  '@swc/core': true
  esbuild: true
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@graphql-codegen/typescript-react-apollo@4.4.3-alpha-20260808101442-e439530add2acc6e119f54b148ccb537e4d0a7ec'
  - '@graphql-codegen/plugin-helpers@7.2.0'
patchedDependencies:
  '@graphql-codegen/cli@7.3.1': patches/@graphql-codegen__cli@7.3.1.patch
