packages:
  - 'packages/*'
  - 'tools/*'
allowBuilds:
  '@swc/core': true
  esbuild: true
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@graphql-codegen/cli'
  - '@graphql-codegen/plugin-helpers'
