import type { ERRORTYPERESOLVERS } from './../../types.gen';
export const ErrorType: ERRORTYPERESOLVERS = {
  NOT_FOUND: 'NOT_FOUND',
  INPUT_VALIDATION_ERROR: 'INPUT_VALIDATION_ERROR',
  FORBIDDEN_ERROR: 'FORBIDDEN_ERROR',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
};
