name: CI

on:
  pull_request:
    branches:
      - master
      - master-next

env:
  node-version: '18.x'

jobs:
  precheck:
    name: Check jobs to run
    runs-on: ubuntu-22.04
    outputs:
      affected-typescript-resolver-files: ${{ steps.affected.outputs.typescript-resolver-files }}
      affected-typescript-resolver-files-e2e: ${{ steps.affected.outputs.typescript-resolver-files-e2e }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: Check affected projects
        id: affected
        run: |
          echo "typescript-resolver-files=$(./tools/ci/bin/check-affected.sh lib typescript-resolver-files origin/master)" >> $GITHUB_OUTPUT
          echo "typescript-resolver-files-e2e=$(./tools/ci/bin/check-affected.sh lib typescript-resolver-files-e2e origin/master)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  typescript-resolver-files:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [18.x, 20.x]
    runs-on: ${{ matrix.os }}
    needs: precheck
    if: ${{ needs.precheck.outputs.affected-typescript-resolver-files == 'true' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: Lint
        run: yarn nx lint typescript-resolver-files

      - name: Test
        run: yarn nx test typescript-resolver-files

      - name: Build
        run: yarn nx build typescript-resolver-files

  typescript-resolver-files-e2e:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [18.x, 20.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    needs: precheck
    if: ${{ needs.precheck.outputs.affected-typescript-resolver-files == 'true' || needs.precheck.outputs.affected-typescript-resolver-files-e2e == 'true' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: e2e
        run: yarn nx e2e typescript-resolver-files-e2e
