on:
  workflow_call:

env:
  node-version: '22.x'

jobs:
  operation-location-migration-e2e:
    strategy:
      matrix:
        os: [ubuntu-22.04] # TODO: test with windows
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            packages/*/node_modules
            tools/*/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: e2e
        run: yarn nx e2e operation-location-migration-e2e
