name: operation-location-migration

on:
  workflow_call:

jobs:
  operation-location-migration:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [22, 24]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node-version }}

      - name: Lint
        run: pnpm nx lint operation-location-migration

      - name: Build
        run: pnpm nx build operation-location-migration
