name: typescript-resolver-files

on:
  workflow_call:

jobs:
  typescript-resolver-files:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [22, 24]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node-version }}

      - name: Lint
        run: pnpm nx lint typescript-resolver-files

      - name: Test
        run: pnpm nx test typescript-resolver-files

      - name: Build
        run: pnpm nx build typescript-resolver-files
